name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd Wedding-Invite
        npm install
      
    - name: Build
      run: |
        cd Wedding-Invite
        npm run build

    - name: Deploy
      run: |
        npx angular-cli-ghpages --dir=dist/your-angular-app
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
